#!/bin/bash

LOG_FILE="/tmp/nagios_conf_update.log"
exec > >(tee $LOG_FILE) 2>&1

GITHOME="/home/nagios/githome"
REPO="${GITHOME}/nagios_conf"

cd "$REPO" || exit 1

if git remote -v update 2>&1 |grep 'origin/master' |grep -q 'up to date'; then
    echo "Sin cambios."
else
    echo "Actualizando la config de nagios."
    /usr/bin/git pull origin master
    /usr/bin/rsync -a "${REPO}/etc/" "/opt/nagios/etc"
    /usr/bin/rsync -a "${REPO}/libexec/" "/opt/nagios/libexec"
    if /opt/nagios/bin/nagios -v /opt/nagios/etc/nagios.cfg; then
        /bin/systemctl reload nagios
    else
        cp "$LOG_FILE" "/home/nagios/$(date +%Y%m%d_%H%M)_nagios_conf_update.log.errors"
    fi
fi

